//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBA.ArenaManagement.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arena
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public string GeneralInformation { get; set; }
        public string Capacities { get; set; }
        public string Suites { get; set; }
        public string PremiumAreas { get; set; }
        public string TechnologyBroadcastInfo { get; set; }
        public string FoodAndBeverage { get; set; }
        public string ArenaOperations { get; set; }
        public string Security { get; set; }
        public string PracticeFacilities { get; set; }
        public string Sustainability { get; set; }
        public string Gallery { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string Location { get; set; }
        public string ArchitecturalInformation { get; set; }
    }
}
