//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBA.ArenaManagement.WebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UiField
    {
        public int Id { get; set; }
        public string FieldText { get; set; }
        public string FieldType { get; set; }
        public string FieldValues { get; set; }
        public string FieldCss { get; set; }
        public Nullable<int> FieldOrder { get; set; }
        public string FieldCategory { get; set; }
        public bool IsCategoryExpandable { get; set; }
        public string FieldSubCategory { get; set; }
        public bool IsFieldVisibleToPublic { get; set; }
        public bool IsNbaNoteFieldEnabled { get; set; }
        public string FieldDescription { get; set; }
        public string PlaceHolderText { get; set; }
        public Nullable<int> Min { get; set; }
        public Nullable<int> Max { get; set; }
        public Nullable<decimal> Step { get; set; }
        public bool NbaOnlyField { get; set; }
        public bool ShowDescriptionAsText { get; set; }
        public string InputMask { get; set; }
        public bool IsTeamNoteFieldEnabled { get; set; }
    }
}
